name: YoFan View Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pyyaml playwright
          python -m playwright install

      - name: Run the bot
        run: python main.py

      - name: Commit view updates
        run: |
          git config user.name "yofan-bot"
          git config user.email "bot@example.com"
          git add views.json
          git commit -m "update views count" || echo "No changes"
          git push
